### ISSUE TITLE
transition cause focus problem

### ISSUE THREAD

**Issue by johnchenkzy** [h16nning/typora-gitbook-theme#24]
In Windows 10 system , Typora version : 0.10.11. if not focus(select) on sidebar item,sidebar drop item will flash across . i debug this issue, It's cause by transition code.
![3](https://user-images.githubusercontent.com/16695997/121301192-68439100-c92a-11eb-9d7c-3135105655dd.gif)

```css
.file-tree-node:not(.file-node-root):not(.file-node-expanded)
    .file-node-background {
    transition-duration: 0.2s;
    transition-property: background-color;
}
```
remove this code, problem resolve. maybe another solution?
